import { MongooseModule } from '@nestjs/mongoose'

import {
  AppModel,
  AppSchema,
  FormAnalyticModel,
  FormAnalyticSchema,
  FormModel,
  FormReportModel,
  FormReportSchema,
  FormSchema,
  IntegrationModel,
  IntegrationSchema,
  ProjectGroupModel,
  ProjectGroupSchema,
  ProjectMemberModel,
  ProjectMemberSchema,
  ProjectModel,
  ProjectSchema,
  SubmissionIpLimitModel,
  SubmissionIpLimitSchema,
  SubmissionModel,
  SubmissionSchema,
  TeamActivityModel,
  TeamActivitySchema,
  TeamInvitationModel,
  TeamInvitationSchema,
  TeamMemberModel,
  TeamMemberSchema,
  TeamModel,
  TeamSchema,
  TemplateModel,
  TemplateSchema,
  UserModel,
  UserSchema,
  UserSocialAccountModel,
  UserSocialAccountSchema
} from './index'

export const ModelModule = MongooseModule.forFeature([
  { name: FormModel.name, schema: FormSchema },
  { name: FormAnalyticModel.name, schema: FormAnalyticSchema },
  { name: FormReportModel.name, schema: FormReportSchema },
  { name: IntegrationModel.name, schema: IntegrationSchema },
  { name: SubmissionModel.name, schema: SubmissionSchema },
  { name: SubmissionIpLimitModel.name, schema: SubmissionIpLimitSchema },
  { name: TeamModel.name, schema: TeamSchema },
  { name: TeamActivityModel.name, schema: TeamActivitySchema },
  { name: TeamInvitationModel.name, schema: TeamInvitationSchema },
  { name: TeamMemberModel.name, schema: TeamMemberSchema },
  { name: TemplateModel.name, schema: TemplateSchema },
  { name: UserModel.name, schema: UserSchema },
  { name: UserSocialAccountModel.name, schema: UserSocialAccountSchema },
  { name: AppModel.name, schema: AppSchema },
  { name: ProjectModel.name, schema: ProjectSchema },
  { name: ProjectGroupModel.name, schema: ProjectGroupSchema },
  { name: ProjectMemberModel.name, schema: ProjectMemberSchema }
])
